"""create Siren tables

Revision ID: 20260820_09
Revises: 20260820_08
Create Date: 2026-08-20
"""
from alembic import op
import sqlalchemy as sa
revision="20260820_09"; down_revision="20260820_08"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("provider_applications",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("provider_type",sa.String(30),nullable=False),sa.Column("business_name",sa.String(160),nullable=False),sa.Column("contact_name",sa.String(120),nullable=False),sa.Column("phone",sa.String(15),nullable=False),sa.Column("email",sa.String(320),nullable=False),sa.Column("address",sa.String(255),nullable=False),sa.Column("area",sa.String(120),nullable=False),sa.Column("city",sa.String(80),nullable=False),sa.Column("state",sa.String(80),nullable=False),sa.Column("pincode",sa.String(6),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("admin_notes",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False)); op.create_index("ix_provider_applications_user_id","provider_applications",["user_id"])
    op.create_table("emergency_providers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),unique=True,nullable=False),sa.Column("provider_type",sa.String(30),nullable=False),sa.Column("business_name",sa.String(160),nullable=False),sa.Column("contact_name",sa.String(120),nullable=False),sa.Column("phone",sa.String(15),nullable=False),sa.Column("email",sa.String(320),nullable=False),sa.Column("address",sa.String(255),nullable=False),sa.Column("area",sa.String(120),nullable=False),sa.Column("city",sa.String(80),nullable=False),sa.Column("state",sa.String(80),nullable=False),sa.Column("pincode",sa.String(6),nullable=False),sa.Column("is_verified",sa.Boolean(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("is_online",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False)); op.create_index("ix_emergency_providers_user_id","emergency_providers",["user_id"])
    op.create_table("emergency_requests",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("request_number",sa.String(20),unique=True,nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("emergency_type",sa.String(40),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("phone",sa.String(15),nullable=False),sa.Column("address",sa.String(255),nullable=False),sa.Column("area",sa.String(120),nullable=False),sa.Column("city",sa.String(80),nullable=False),sa.Column("state",sa.String(80),nullable=False),sa.Column("pincode",sa.String(6),nullable=False),sa.Column("latitude",sa.Float()),sa.Column("longitude",sa.Float()),sa.Column("status",sa.String(30),nullable=False),sa.Column("priority",sa.String(20),nullable=False),sa.Column("provider_id",sa.Integer(),sa.ForeignKey("emergency_providers.id")),sa.Column("accepted_at",sa.DateTime(timezone=True)),sa.Column("assigned_at",sa.DateTime(timezone=True)),sa.Column("on_the_way_at",sa.DateTime(timezone=True)),sa.Column("arrived_at",sa.DateTime(timezone=True)),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.Column("cancelled_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False)); op.create_index("ix_emergency_requests_user_id","emergency_requests",["user_id"])
    op.create_table("notifications",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("title",sa.String(160),nullable=False),sa.Column("message",sa.Text(),nullable=False),sa.Column("type",sa.String(30),nullable=False),sa.Column("is_read",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("CURRENT_TIMESTAMP"),nullable=False)); op.create_index("ix_notifications_user_id","notifications",["user_id"])

def downgrade():
    op.drop_table("notifications"); op.drop_table("emergency_requests"); op.drop_table("emergency_providers"); op.drop_table("provider_applications")
