import { useEffect, useState } from 'react'
import { ArrowLeft, MapPin, Plus, WalletCards, Tag } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import api from '../services/api'
import CartSummary from '../components/CartSummary'
import EmptyState from '../components/EmptyState'
import { useCart } from '../context/CartContext'

const blank = { full_name: '', phone: '', address_line: '', area: '', city: 'Bengaluru', state: 'Karnataka', pincode: '', is_default: false }

export default function Checkout() {
  const { items, cart, refreshCart } = useCart(); const navigate = useNavigate(); const [addresses, setAddresses] = useState([]); const [selected, setSelected] = useState(''); const [form, setForm] = useState(blank); const [adding, setAdding] = useState(false); const [couponCode, setCouponCode] = useState(''); const [error, setError] = useState(''); const [placing, setPlacing] = useState(false)
  useEffect(() => { api.get('/api/addresses').then(({ data }) => setAddresses(data)).catch(() => setError('Unable to load addresses.')) }, [])
  async function saveAddress(event) { event.preventDefault(); try { const { data } = await api.post('/api/addresses', form); setAddresses((current) => [data, ...current]); setSelected(String(data.id)); setAdding(false); setForm(blank) } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to save address.') } }
  async function placeOrder() { if (!selected) { setError('Select a delivery address.'); return } setPlacing(true); setError(''); try { const { data } = await api.post('/api/orders', { address_id: Number(selected), payment_method: 'CASH_ON_DELIVERY', coupon_code: couponCode.trim() || null }); await refreshCart(); navigate(`/orders/${data.id}`) } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to place order.') } finally { setPlacing(false) } }
  if (!items.length) return <div className="commerce-page"><EmptyState title="Your cart is empty." detail="Add something before checkout." /></div>
  return <div className="commerce-page"><Link to="/cart" className="back-link"><ArrowLeft size={15} /> Cart</Link><div className="page-intro"><span className="section-kicker">Almost there</span><h1>Checkout</h1><p>Confirm your delivery details and payment method.</p></div>{error && <div className="form-error" role="alert">{error}</div>}<div className="commerce-layout"><div className="checkout-main"><section className="checkout-section"><div className="checkout-heading"><h2><MapPin size={19} /> Delivery Address</h2><button type="button" onClick={() => setAdding(!adding)}><Plus size={15} /> Add new</button></div>{addresses.map((address) => <label className={`address-option ${selected === String(address.id) ? 'selected' : ''}`} key={address.id}><input type="radio" name="address" checked={selected === String(address.id)} onChange={() => setSelected(String(address.id))} /><span><strong>{address.full_name}</strong><small>{address.address_line}, {address.area}, {address.city}, {address.state} - {address.pincode}</small></span></label>)}{!addresses.length && <EmptyState title="Add a delivery address." />}{adding && <form className="address-form" onSubmit={saveAddress}>{Object.keys(blank).filter((key) => key !== 'is_default').map((key) => <input key={key} name={key} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} placeholder={key.replaceAll('_', ' ')} required />)}<button className="auth-submit">Save Address</button></form>}</section><section className="checkout-section"><h2><Tag size={19} /> Coupon</h2><input value={couponCode} onChange={(event) => setCouponCode(event.target.value.toUpperCase())} maxLength="40" placeholder="Enter coupon code" /></section><section className="checkout-section"><h2><WalletCards size={19} /> Payment Method</h2><label className="payment-option selected"><input type="radio" checked readOnly /><span><strong>Cash on Delivery</strong><small>Pay when your order arrives.</small></span></label></section></div><aside className="checkout-aside"><CartSummary cart={cart} /><button className="auth-submit checkout-submit" type="button" disabled={placing} onClick={placeOrder}>{placing ? 'Placing order...' : 'Place order'}</button></aside></div></div>
}
