import { useEffect, useState } from 'react'
import { ArrowLeft, Ban } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import api from '../services/api'
import ErrorState from '../components/ErrorState'
import LoadingSpinner from '../components/LoadingSpinner'
import OrderStatusTimeline from '../components/OrderStatusTimeline'

export default function OrderDetails() { const { id } = useParams(); const [order, setOrder] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const load = () => api.get(`/api/orders/${id}`).then(({ data }) => setOrder(data)).catch(() => setError('Order not found.')).finally(() => setLoading(false)); useEffect(load, [id]); async function cancel() { if (!window.confirm('Are you sure you want to cancel this order?')) return; try { setOrder((await api.post(`/api/orders/${id}/cancel`)).data) } catch (requestError) { setError(requestError.response?.data?.detail || 'Order cannot be cancelled.') } } if (loading) return <LoadingSpinner label="Loading order..." />; if (error && !order) return <ErrorState message={error} />; return <div className="commerce-page"><Link to="/orders" className="back-link"><ArrowLeft size={15} /> Orders</Link><div className="page-intro"><span className="section-kicker">Order tracking</span><h1>#{order.order_number}</h1><p>Placed {new Date(order.created_at).toLocaleString()}</p></div><div className="order-detail-card"><OrderStatusTimeline status={order.status} /><div className="order-detail-items">{order.items.map((item) => <div key={item.id}><span>{item.item_name} x {item.quantity}</span><b>₹{Number(item.total_price).toFixed(0)}</b></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><b>₹{Number(order.subtotal).toFixed(0)}</b></div><div><span>Delivery</span><b>₹{Number(order.delivery_fee).toFixed(0)}</b></div><div className="summary-total"><strong>Total</strong><strong>₹{Number(order.total_amount).toFixed(0)}</strong></div></div><p className="order-address"><strong>Delivery</strong><br />{order.delivery_address}</p><p className="payment-note">Payment: {order.payment_method.replaceAll('_', ' ')} ({order.payment_status})</p>{error && <div className="form-error">{error}</div>}{['PENDING', 'CONFIRMED'].includes(order.status) && <button type="button" className="cancel-order" onClick={cancel}><Ban size={15} /> Cancel Order</button>}</div></div> }
